# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0007_object_pk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='client',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='client id'),
        ),
    ]
